name: CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin release...
        uses: actions/checkout@v2

      - name: Use Node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc && npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
